/* Generated by Yosys 0.18+40 (git sha1 42721b6a1, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module fulladder1(a, b, cin, s, cout);
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  wire _7_;
  wire _8_;
  wire _9_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output s;
  wire s;
  wire t1;
  wire t2;
  wire t3;
  wire t4;
  wire t5;
  wire t6;
  wire t7;
  wire \y1:77 ;
  wire \y2:80 ;
  wire \y3:83 ;
  wire \y4:86 ;
  wire \y5:89 ;
  wire \y6:92 ;
  wire \y7:95 ;
  wire \y8:98 ;
  wire \y9:101 ;
  nandgate y1 (
    .l(a),
    .m(b),
    .y(_0_)
  );
  nandgate y2 (
    .l(a),
    .m(t1),
    .y(_1_)
  );
  nandgate y3 (
    .l(b),
    .m(t1),
    .y(_2_)
  );
  nandgate y4 (
    .l(t2),
    .m(t3),
    .y(_3_)
  );
  nandgate y5 (
    .l(t4),
    .m(t5),
    .y(_4_)
  );
  nandgate y6 (
    .l(t4),
    .m(t5),
    .y(_5_)
  );
  nandgate y7 (
    .l(t6),
    .m(t7),
    .y(_6_)
  );
  nandgate y8 (
    .l(t6),
    .m(t7),
    .y(_7_)
  );
  nandgate y9 (
    .l(t1),
    .m(t5),
    .y(_8_)
  );
  assign t1 = \y1:77 ;
  assign t2 = \y2:80 ;
  assign t3 = \y3:83 ;
  assign t4 = \y4:86 ;
  assign t5 = 1'hx;
  assign t6 = _9_;
  assign t7 = \y7:95 ;
  assign \y1:77  = _0_;
  assign \y2:80  = _1_;
  assign \y3:83  = _2_;
  assign \y4:86  = _3_;
  assign \y5:89  = _4_;
  assign \y6:92  = _5_;
  assign \y7:95  = _6_;
  assign \y8:98  = _7_;
  assign \y9:101  = _8_;
  assign _9_ = \y5:89 ;
  assign _9_ = \y6:92 ;
  assign s = \y8:98 ;
  assign cout = \y9:101 ;
endmodule

module nandgate(l, m, y);
  wire _0_;
  wire _1_;
  input l;
  wire l;
  input m;
  wire m;
  output y;
  wire y;
  assign _1_ = l & m;
  assign _0_ = ~ _1_;
  assign y = _0_;
endmodule

module rc_adder(A, B, CIN, S, COUT);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input [7:0] A;
  wire [7:0] A;
  input [7:0] B;
  wire [7:0] B;
  input CIN;
  wire CIN;
  output COUT;
  wire COUT;
  output [7:0] S;
  wire [7:0] S;
  wire [6:0] c;
  wire \u1:4 ;
  wire \u1:5 ;
  wire \u2:1.u3:13 ;
  wire \u2:1.u3:14 ;
  wire \u2:2.u3:22 ;
  wire \u2:2.u3:23 ;
  wire \u2:3.u3:31 ;
  wire \u2:3.u3:32 ;
  wire \u2:4.u3:40 ;
  wire \u2:4.u3:41 ;
  wire \u2:5.u3:49 ;
  wire \u2:5.u3:50 ;
  wire \u2:6.u3:58 ;
  wire \u2:6.u3:59 ;
  wire \u4:67 ;
  wire \u4:68 ;
  fulladder1 u1 (
    .a(A[0]),
    .b(B[0]),
    .cin(CIN),
    .cout(_08_),
    .s(_00_)
  );
  fulladder1 \u2:1.u3  (
    .a(A[1]),
    .b(B[1]),
    .cin(c[0]),
    .cout(_10_),
    .s(_09_)
  );
  fulladder1 \u2:2.u3  (
    .a(A[2]),
    .b(B[2]),
    .cin(c[1]),
    .cout(_12_),
    .s(_11_)
  );
  fulladder1 \u2:3.u3  (
    .a(A[3]),
    .b(B[3]),
    .cin(c[2]),
    .cout(_14_),
    .s(_13_)
  );
  fulladder1 \u2:4.u3  (
    .a(A[4]),
    .b(B[4]),
    .cin(c[3]),
    .cout(_01_),
    .s(_15_)
  );
  fulladder1 \u2:5.u3  (
    .a(A[5]),
    .b(B[5]),
    .cin(c[4]),
    .cout(_03_),
    .s(_02_)
  );
  fulladder1 \u2:6.u3  (
    .a(A[6]),
    .b(B[6]),
    .cin(c[5]),
    .cout(_05_),
    .s(_04_)
  );
  fulladder1 u4 (
    .a(A[7]),
    .b(B[7]),
    .cin(c[6]),
    .cout(_07_),
    .s(_06_)
  );
  assign c = { \u2:6.u3:59 , \u2:5.u3:50 , \u2:4.u3:41 , \u2:3.u3:32 , \u2:2.u3:23 , \u2:1.u3:14 , \u1:5  };
  assign \u1:4  = _00_;
  assign \u1:5  = _08_;
  assign \u2:1.u3:13  = _09_;
  assign \u2:1.u3:14  = _10_;
  assign \u2:2.u3:22  = _11_;
  assign \u2:2.u3:23  = _12_;
  assign \u2:3.u3:31  = _13_;
  assign \u2:3.u3:32  = _14_;
  assign \u2:4.u3:40  = _15_;
  assign \u2:4.u3:41  = _01_;
  assign \u2:5.u3:49  = _02_;
  assign \u2:5.u3:50  = _03_;
  assign \u2:6.u3:58  = _04_;
  assign \u2:6.u3:59  = _05_;
  assign \u4:67  = _06_;
  assign \u4:68  = _07_;
  assign S = { \u4:67 , \u2:6.u3:58 , \u2:5.u3:49 , \u2:4.u3:40 , \u2:3.u3:31 , \u2:2.u3:22 , \u2:1.u3:13 , \u1:4  };
  assign COUT = \u4:68 ;
endmodule